name: flutter_kronos
description: Flutter Kronos plugin project.
version: 0.0.2+1
homepage: 'https://github.com/hautvfami/flutter-kronos'
repository: 'https://github.com/hautvfami/flutter-kronos'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.stark.flutter_kronos
        pluginClass: FlutterKronosPlugin
      ios:
        pluginClass: FlutterKronosPlugin