name: flutter_kronos
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:
repository: 'https://github.com/hautvfami/flutter-kronos'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    android:
      package: com.vingroup.retails.flutter_kronos
      pluginClass: FlutterKronosPlugin
    ios:
      pluginClass: FlutterKronosPlugin